language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt511
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake qt51base qt51quickcontrols
before_script:
  - source /opt/qt51/bin/qt51-env.sh
  - cd src
  - cmake .
script:
  - make

